export { combine, combineApply } from './combine';
import { distinct, distinctStrictEquality } from './distinct';
export { distinct, distinctStrictEquality };
export const skip = distinct;
export const skipStrictEquality = distinctStrictEquality;
export { flatten } from './flatten';
export { history } from './history';
export { map } from './map';
export { pick } from './pick';
export { pipeByProperties } from './pipe-by-properties';
export { pluck } from './pluck';
export { reduce } from './reduce';
export { splitByProperties } from './split-by-properties';
export { throttle } from './throttle';
